module.exports = {
  SYSTEM_IP: "http://localhost:3001/",
  MEDICAL_REPORTS: '/Users/admin/uploads/',
  TEACHER_RESUME: '/Users/admin/resume/',
  ROLES: {
    SUPER_ADMIN: 1,
    ADMIN: 2,
    PARENT: 3,
    TEACHER: 4
  },
  DEFAULT_PAGE_NUMBER: 0,
  DEFAULT_PAGE_SIZE: 20,
  ACCOUNT_WITH_EMAIL_EXIST: "Account already exist with this email",
  INVALID_CREDENTIAL: "Invalid credential",
  INVALID_REQUEST: "Invalid request",
  INCORRECT_PASSWORD: "Incorrect password",
  DATA_LOAD_SUCCESS: "Data loaded successfully",
  CHILD_ADDED_SUCCESS: "Child added successfully",
  ACCOUNT_NOT_EXIST: "User does not exist",
  ACCOUNT_DELETE_MSG: "Your account has been deleted. Please contact with admin.",
  FORGOT_EMAIL_SUCCESS: "Forgot password has been sent to your email",
  RESET_PASSWORD_LINK_EXPIRED: "Link has been expired",
  PASSWORD_RESET_SUCCESS: "Password has been changed successfully",
  SUCCESS: "Data loaded Successfully",
  SUCCESS_MSG: "Data saved successfully",
  USER_CREATED_SUCCESS: "User created successfully",
  TEACHER_UPDATE_SUCCESS: "Teacher has been updated",
  CLASS_ADD_SUCCESS: "Class has been added successfully",
  CLASS_UPDATE_SUCCESS: "Class updated successfully",
  CLASS_DELETE_SUCCESS: "Class deleted successfully",
  USER_UPDATE_SUCCESS: "Profile updated successfully",
  USER_DELETE_SUCCESS: "User deleted successfully",
  ANNOUNCEMENT_CREATED_SUCCESS: "Announcement has been created successfully",
  ANNOUNCEMENT_UPDATED_SUCCESS: "Announcement has been updated successfully",
  ANNOUNCEMENT_DELETED_SUCCESS: "Announcement has been deleted successfully",
  TEACHER_DELETE_SUCCESS: "Teacher has been deleted successfully",
  CHILD_UPDATED_SUCCESS: "Child has been updated successfully",
  CHILD_DELETE_SUCCESS: "Child has been deleted successfully",
  ANNOUNCEMENT_ACTIVE_SUCCESS: "Status has been updated successfully",
  APPROVED_SUCCESS: "User has been approved successfully",
  UNAPPROVED_SUCCESS: "User has been un-approved successfully",
  SUPPORT_REPLY_SUCCESS: "Support response sent successfully",
  ACCOUNT_UNDER_APPROVED: "Your account has been successfully created. We will notify you on your registered email once it is activated/approved.",
  DELETED_SUCCESS: "Deleted successfully",
  ACTIVE_SUCCESS: "Account active successfully",
  INACTIVE_SUCCESS: "Account in-active successfully",
  RENEWAL_ADMISSION_SUCCESS: "Admission has been renew successfully",

  USER_ID_REQUIRED: 'User id field is required',
  CLASS_NAME_EXIST: 'Class name already exist',
  ACCOUNT_NOT_APPROVED: " Your Account is under approval. We will notify you on your registered email once it is activated/approved.",
  ANNOUNCEMENT_ID_REQUIRED: "Announcement id field is required",
  TEACHER_ID_REQUIRED: "Teacher id field is required",
  CHILD_ID_REQUIRED: "Child id field is required",
  ID_REQUIRED: "Id field is required",

  INCIDENT_ID_REQUIRED: 'Incident id field is required',
  INCIDNT_ALREADY_EXIST: 'Incident with this name and date already exist',
  INCIDENT_ADD_SUCCESS: "Incident has been added successfully",
  INCIDENT_UPDATE_SUCCESS: "Incident updated successfully",
  INCIDENT_DELETE_SUCCESS: "Incident deleted successfully",
  NO_FILES: "Files Required"
};
